const constant = {
  DETAIL: 'Detail',

  EVENT_GOTO_SIGNIN: 'EVENT_GOTO_SIGNIN',
  EVENT_SIGNIN_SUCCESS: 'EVENT_SIGNIN_SUCCESS',
  EVENT_SIGN_OUT: 'EVENT_SIGN_OUT',
  EVENT_SNS_SIGNIN_AGAIN: 'EVENT_SNS_SIGNIN_AGAIN',

  VERSION_APP: '1.0.0',
  KEY_ACCESS_ID: 'MzNhc3NlY2VLZXkzMTU4NjU4NzI4MDg4NDgz',
  KEY_SECRET: 'MzRzY3JldEtleTMxNTg2NTg3MzQ2MjM2NTkie',
  //asynstorage
  SHOW_INTRO: 'SHOW_INTRO',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  USER_TOKEN: 'USER_TOKEN',

  BASE_URL: 'http://dev-api.minitv.io/v1',
};
export default constant;
